@extends('layouts.app')
@section('title','Riwayat Transaksi')
@push('styles')<link rel="stylesheet" href="{{ asset('bundles/datatables/datatables.min.css') }}">@endpush
@push('vendor-scripts')<script src="{{ asset('bundles/datatables/datatables.min.js') }}"></script>@endpush
@section('content')
<div class="section-header"><h1>Riwayat Transaksi</h1><div class="section-header-breadcrumb"><div class="breadcrumb-item"><a href="{{ route('dashboard') }}">Dashboard</a></div><div class="breadcrumb-item active">Riwayat Transaksi</div></div></div>
<div class="section-body"><div class="card"><div class="card-header"><h4>Filter transaksi</h4></div><div class="card-body"><form method="GET" action="{{ route('transactions.index') }}"><div class="form-row align-items-end"><div class="form-group col-md-4"><label for="start_date">Tanggal mulai</label><input id="start_date" name="start_date" type="date" class="form-control" value="{{ $startDate }}"></div><div class="form-group col-md-4"><label for="end_date">Tanggal selesai</label><input id="end_date" name="end_date" type="date" class="form-control" value="{{ $endDate }}"></div><div class="form-group col-md-3"><label for="status">Status</label><select id="status" name="status" class="form-control"><option value="">Semua status</option>@foreach($statuses as $status)<option value="{{ $status->value }}" @selected(request('status')===$status->value)>{{ ['completed'=>'Selesai','draft'=>'Draft','voided'=>'Void','discarded'=>'Dibuang'][$status->value] }}</option>@endforeach</select></div><div class="form-group col-md-1"><button class="btn btn-primary" type="submit"><i class="fas fa-filter"></i></button></div></div></form></div></div>
<div class="card"><div class="card-header"><h4>Daftar transaksi</h4></div><div class="card-body"><div class="table-responsive"><table class="table table-striped" id="transactions-table"><thead><tr><th>Waktu</th><th>Invoice/Draft</th><th>Kasir</th><th>Item</th><th>Metode</th><th>Total</th><th>Status</th><th>Aksi</th></tr></thead><tbody>@forelse($sales as $sale)<tr><td data-order="{{ $sale->created_at->timestamp }}">{{ $sale->created_at->format('d/m/Y H:i') }}</td><td>{{ $sale->invoice_number ?: $sale->draft_number }}</td><td>{{ optional($sale->completedBy ?: $sale->user)->name }}</td><td>{{ $sale->items_count }}</td><td>{{ $sale->payment_method?->value ? strtoupper($sale->payment_method->value) : '-' }}</td><td>{{ format_rupiah((int)$sale->total) }}</td><td><span class="badge badge-{{ $sale->status->value === 'completed' ? 'success' : ($sale->status->value === 'voided' ? 'danger' : 'warning') }}">{{ ['completed'=>'Selesai','draft'=>'Draft','voided'=>'Void','discarded'=>'Dibuang'][$sale->status->value] }}</span></td><td><a class="btn btn-sm btn-outline-primary" href="{{ route('transactions.show',$sale) }}">Detail</a></td></tr>@empty<tr><td colspan="8" class="text-center py-4">Belum ada transaksi pada periode ini.</td></tr>@endforelse</tbody></table></div></div></div></div>
@endsection
@push('scripts')<script>$(function(){ $('#transactions-table').DataTable({pageLength:10,ordering:true,responsive:true,dom:'Bfrtip',buttons:['copy','csv','excel','pdf','print']}); });</script>@endpush
