@extends('layouts.app')
@section('title','Log Aktivitas')
@push('styles')<link rel="stylesheet" href="{{ asset('bundles/datatables/datatables.min.css') }}">@endpush
@push('vendor-scripts')<script src="{{ asset('bundles/datatables/datatables.min.js') }}"></script>@endpush
@section('content')
<div class="section-header"><h1>Log Aktivitas</h1></div><div class="section-body"><div class="card"><div class="card-header"><h4>Filter log (maksimal 30 hari default)</h4></div><div class="card-body"><form method="GET"><div class="form-row align-items-end"><div class="form-group col-md-4"><label for="start_date">Tanggal mulai</label><input id="start_date" name="start_date" type="date" class="form-control daterange" value="{{ $startDate }}"></div><div class="form-group col-md-4"><label for="end_date">Tanggal selesai</label><input id="end_date" name="end_date" type="date" class="form-control daterange" value="{{ $endDate }}"></div><div class="form-group col-md-2"><button class="btn btn-primary">Terapkan</button></div></div></form></div></div><div class="card"><div class="card-header"><h4>Aktivitas sistem</h4></div><div class="card-body"><div class="table-responsive"><table id="system-logs-table" class="table table-striped"><thead><tr><th>Waktu</th><th>Pengguna</th><th>Aksi</th><th>Tabel</th><th>Record</th><th>Method</th><th>IP</th><th>Detail</th></tr></thead><tbody>@forelse($logs as $log)<tr><td data-order="{{ $log->created_at->timestamp }}">{{ $log->created_at->format('d/m/Y H:i:s') }}</td><td>{{ optional($log->user)->name ?: 'Sistem' }}</td><td>{{ $log->action }}</td><td>{{ $log->table_name ?: '-' }}</td><td>{{ $log->record_id ?: '-' }}</td><td>{{ $log->method ?: '-' }}</td><td>{{ $log->ip_address ?: '-' }}</td><td><button type="button" class="btn btn-sm btn-outline-primary log-detail" data-toggle="modal" data-target="#log-detail-modal" data-old="{{ json_encode($log->old_values ?: [], JSON_HEX_TAG|JSON_HEX_APOS|JSON_HEX_QUOT|JSON_HEX_AMP) }}" data-new="{{ json_encode($log->new_values ?: [], JSON_HEX_TAG|JSON_HEX_APOS|JSON_HEX_QUOT|JSON_HEX_AMP) }}">Lihat</button></td></tr>@empty<tr><td colspan="8" class="text-center">Belum ada log pada periode ini.</td></tr>@endforelse</tbody></table></div></div></div></div>
<div class="modal fade" id="log-detail-modal" tabindex="-1" role="dialog"><div class="modal-dialog modal-lg" role="document"><div class="modal-content"><div class="modal-header"><h5 class="modal-title">Detail perubahan</h5><button type="button" class="close" data-dismiss="modal"><span>&times;</span></button></div><div class="modal-body"><h6>Data lama</h6><pre id="log-old" class="bg-light p-2"></pre><h6>Data baru</h6><pre id="log-new" class="bg-light p-2"></pre></div></div></div></div>
@endsection
@push('scripts')<script>$(function(){ $('#system-logs-table').DataTable({pageLength:10,responsive:true,order:[[0,'desc']],dom:'Bfrtip',buttons:['copy','csv','excel','pdf','print']}); $('.log-detail').on('click',function(){var b=$(this); var safe=function(value){try{return JSON.stringify(JSON.parse(value),null,2);}catch(e){return '{}';}}; document.getElementById('log-old').textContent=safe(b.attr('data-old')); document.getElementById('log-new').textContent=safe(b.attr('data-new'));});});</script>@endpush
