@extends('layouts.app')
@section('title','Dashboard')
@section('content')
<div class="section-header"><h1>Dashboard</h1><div class="section-header-breadcrumb"><div class="breadcrumb-item active">Dashboard</div></div></div>
<div class="section-body"><div class="row"><div class="col-lg-3 col-md-6 col-12"><div class="card card-statistic-1"><div class="card-icon bg-primary"><i class="fas fa-money-bill-wave" aria-hidden="true"></i></div><div class="card-wrap"><div class="card-header"><h4>Omzet hari ini</h4></div><div class="card-body">{{ format_rupiah($todaySales) }}</div></div></div></div><div class="col-lg-3 col-md-6 col-12"><div class="card card-statistic-1"><div class="card-icon bg-success"><i class="fas fa-receipt" aria-hidden="true"></i></div><div class="card-wrap"><div class="card-header"><h4>Transaksi hari ini</h4></div><div class="card-body">{{ $todayTransactions }}</div></div></div></div><div class="col-lg-3 col-md-6 col-12"><div class="card card-statistic-1"><div class="card-icon bg-warning"><i class="fas fa-clipboard-list" aria-hidden="true"></i></div><div class="card-wrap"><div class="card-header"><h4>Draft aktif</h4></div><div class="card-body">{{ $activeDrafts }}</div></div></div></div>@if($isAdmin)<div class="col-lg-3 col-md-6 col-12"><div class="card card-statistic-1"><div class="card-icon bg-danger"><i class="fas fa-cubes" aria-hidden="true"></i></div><div class="card-wrap"><div class="card-header"><h4>Stok menipis</h4></div><div class="card-body">{{ $lowCount }}</div></div></div></div>@endif</div>
@if($isAdmin)<div class="row"><div class="col-lg-8"><div class="card"><div class="card-header"><h4>Penjualan 7 hari terakhir</h4></div><div class="card-body"><div id="sales-chart" style="min-height:280px"></div></div></div></div><div class="col-lg-4"><div class="card"><div class="card-header"><h4>Stok menipis</h4></div><div class="card-body">@forelse($lowStock as $product)<div class="d-flex justify-content-between border-bottom py-2"><span>{{ $product->name }}</span><span class="badge badge-danger">{{ $product->stock }}</span></div>@empty<div class="empty-state" data-height="100">Tidak ada stok menipis.</div>@endforelse</div></div></div></div><div class="row"><div class="col-12"><div class="card"><div class="card-header"><h4>Produk terlaris bulan ini</h4></div><div class="card-body"><div class="table-responsive"><table class="table table-striped" id="dashboard-top-products"><thead><tr><th>Produk</th><th>Qty</th><th>Omzet</th></tr></thead><tbody>@forelse($topProducts as $product)<tr><td>{{ $product->product_name }}</td><td>{{ $product->quantity }}</td><td>{{ format_rupiah((int)$product->omzet) }}</td></tr>@empty<tr><td colspan="3" class="text-center">Belum ada penjualan.</td></tr>@endforelse</tbody></table></div></div></div></div></div>@else<div class="card"><div class="card-body"><h4>Selamat datang, {{ auth()->user()->name }}.</h4><p class="text-muted">Kelola antrean pelanggan melalui halaman kasir.</p><a href="{{ route('pos.index') }}" class="btn btn-primary"><i class="fas fa-cash-register"></i> Buka Kasir</a></div></div>@endif</div>
@endsection
@if($isAdmin)
@push('vendor-scripts')<script src="{{ asset('bundles/apexcharts/apexcharts.min.js') }}"></script>@endpush
@push('scripts')<script>document.addEventListener('DOMContentLoaded',function(){var target=document.querySelector('#sales-chart');if(!target||typeof ApexCharts==='undefined')return;new ApexCharts(target,{chart:{type:'line',height:280,toolbar:{show:false}},series:[{name:'Omzet',data:@json($chartValues)}],xaxis:{categories:@json($chartLabels)},yaxis:{labels:{formatter:function(value){return 'Rp '+Number(value).toLocaleString('id-ID');}}},stroke:{curve:'smooth'}}).render();});</script>@endpush
@endif
