@extends('layouts.app')
@section('title','Laporan Stok')
@push('styles')<link rel="stylesheet" href="{{ asset('bundles/datatables/datatables.min.css') }}">@endpush
@push('vendor-scripts')<script src="{{ asset('bundles/datatables/datatables.min.js') }}"></script>@endpush
@section('content')
<div class="section-header"><h1>Laporan Stok</h1></div><div class="section-body"><form class="card card-body mb-3"><div class="form-row align-items-end"><div class="form-group col-md-4"><label for="start_date">Tanggal mulai</label><input id="start_date" name="start_date" type="date" class="form-control daterange" value="{{ $startDate }}"></div><div class="form-group col-md-4"><label for="end_date">Tanggal selesai</label><input id="end_date" name="end_date" type="date" class="form-control daterange" value="{{ $endDate }}"></div><div class="form-group col-md-2"><button class="btn btn-primary">Terapkan</button></div></div></form>
<div class="row"><div class="col-md-6"><div class="card card-statistic-1"><div class="card-icon bg-primary"><i class="fas fa-boxes"></i></div><div class="card-wrap"><div class="card-header"><h4>Nilai persediaan</h4></div><div class="card-body">{{ format_rupiah($totalValue) }}</div></div></div></div><div class="col-md-6"><div class="card card-statistic-1"><div class="card-icon bg-danger"><i class="fas fa-exclamation-triangle"></i></div><div class="card-wrap"><div class="card-header"><h4>Stok menipis</h4></div><div class="card-body">{{ $lowCount }}</div></div></div></div></div>
<div class="card"><div class="card-header"><h4>Snapshot stok saat ini</h4></div><div class="card-body"><div class="table-responsive"><table id="stock-report-table" class="table table-striped"><thead><tr><th>SKU</th><th>Produk</th><th>Kategori</th><th>Stok</th><th>Harga beli</th><th>Nilai persediaan</th><th>Status</th></tr></thead><tbody>@forelse($rows as $row)<tr><td>{{ $row->sku }}</td><td>{{ $row->name }}</td><td>{{ $row->category->name }}</td><td>{{ $row->stock }}</td><td>{{ format_rupiah($row->cost_price) }}</td><td>{{ format_rupiah((int)$row->stock*(int)$row->cost_price) }}</td><td>{{ $row->min_stock>0&&$row->stock<=$row->min_stock?'Menipis':'Aman' }}</td></tr>@empty<tr><td colspan="7" class="text-center">Belum ada produk.</td></tr>@endforelse</tbody></table></div></div></div></div></div>
@endsection
@push('scripts')<script>$(function(){ $('#stock-report-table').DataTable({pageLength:10,responsive:true,dom:'Bfrtip',buttons:['copy','csv','excel','pdf','print']}); });</script>@endpush
