@extends('layouts.app')

@section('title', 'Stok')

@push('styles')
    <link rel="stylesheet" href="{{ asset('bundles/datatables/datatables.min.css') }}">
@endpush
@push('vendor-scripts')
    <script src="{{ asset('bundles/datatables/datatables.min.js') }}"></script>
@endpush

@section('content')
<div class="section-header"><h1>Stok</h1><div class="section-header-breadcrumb"><div class="breadcrumb-item"><a href="{{ route('dashboard') }}">Dashboard</a></div><div class="breadcrumb-item active">Stok</div></div></div>
<div class="section-body">
    <div class="card"><div class="card-header"><h4>Filter stok</h4></div><div class="card-body"><form method="GET" action="{{ route('stock.index') }}"><div class="form-row align-items-end"><div class="form-group col-12 col-md-4"><label for="filter_category">Kategori</label><select id="filter_category" name="category_id" class="form-control"><option value="">Semua kategori</option>@foreach ($categories as $category)<option value="{{ $category->id }}" @selected($selectedCategory === $category->id)>{{ $category->name }}</option>@endforeach</select></div><div class="form-group col-12 col-md-4"><div class="custom-control custom-checkbox mb-2"><input type="checkbox" class="custom-control-input" id="low_stock" name="low_stock" value="1" @checked($onlyLowStock)><label class="custom-control-label" for="low_stock">Hanya tampilkan stok menipis</label></div></div><div class="form-group col-12 col-md-4"><button class="btn btn-primary mr-2" type="submit"><i class="fas fa-filter"></i> Terapkan</button><a class="btn btn-light" href="{{ route('stock.index') }}">Reset</a></div></div></form></div></div>
    <div class="card"><div class="card-header"><h4>Daftar stok</h4><div class="card-header-action"><button type="button" class="btn btn-success mr-2" data-toggle="modal" data-target="#modalReceive"><i class="fas fa-plus"></i> Stok masuk</button><button type="button" class="btn btn-warning" data-toggle="modal" data-target="#modalAdjust"><i class="fas fa-clipboard-check"></i> Penyesuaian</button></div></div><div class="card-body"><div class="table-responsive"><table class="table table-striped" id="stock-table"><thead><tr><th>SKU</th><th>Nama</th><th>Kategori</th><th>Stok</th><th>Min. stok</th><th>Status</th></tr></thead><tbody>@forelse ($products as $product)<tr><td>{{ $product->sku }}</td><td>{{ $product->name }}</td><td>{{ $product->category->name }}</td><td>{{ $product->stock }}</td><td>{{ $product->min_stock }}</td><td>@if ($product->stock === 0)<span class="badge badge-danger">Habis</span>@elseif ($product->min_stock > 0 && $product->stock <= $product->min_stock)<span class="badge badge-warning">Menipis</span>@else<span class="badge badge-success">Aman</span>@endif</td></tr>@empty<tr><td colspan="6" class="text-center py-4">Tidak ada produk yang sesuai filter.</td></tr>@endforelse</tbody></table></div></div></div>
</div>

<div class="modal fade" id="modalReceive" tabindex="-1" role="dialog" aria-labelledby="modalReceiveLabel" aria-hidden="true"><div class="modal-dialog" role="document"><div class="modal-content"><div class="modal-header"><h5 class="modal-title" id="modalReceiveLabel">Stok masuk</h5><button type="button" class="close" data-dismiss="modal" aria-label="Tutup"><span aria-hidden="true">&times;</span></button></div><form method="POST" action="{{ route('stock.receive') }}"><div class="modal-body">@csrf<input type="hidden" name="_modal" value="receive"><div class="form-group"><label for="receive_product_id">Produk</label><select id="receive_product_id" name="product_id" class="form-control @error('product_id') is-invalid @enderror" required><option value="">Pilih produk</option>@foreach ($products as $product)<option value="{{ $product->id }}" @selected(old('product_id') === $product->id)>{{ $product->sku }} - {{ $product->name }} (stok {{ $product->stock }})</option>@endforeach</select>@error('product_id')<div class="invalid-feedback">{{ $message }}</div>@enderror</div><div class="form-group"><label for="receive_quantity">Jumlah masuk</label><input id="receive_quantity" type="number" min="1" name="quantity" class="form-control @error('quantity') is-invalid @enderror" value="{{ old('quantity') }}" required>@error('quantity')<div class="invalid-feedback">{{ $message }}</div>@enderror</div><div class="form-group"><label for="receive_cost_price">Harga beli baru <small class="text-muted">(opsional)</small></label><input id="receive_cost_price" type="number" min="0" name="cost_price" class="form-control @error('cost_price') is-invalid @enderror" value="{{ old('cost_price') }}">@error('cost_price')<div class="invalid-feedback">{{ $message }}</div>@enderror</div><div class="form-group"><label for="receive_note">Catatan <small class="text-muted">(opsional)</small></label><textarea id="receive_note" name="note" rows="3" class="form-control @error('note') is-invalid @enderror">{{ old('note') }}</textarea>@error('note')<div class="invalid-feedback">{{ $message }}</div>@enderror</div></div><div class="modal-footer"><button type="button" class="btn btn-light" data-dismiss="modal">Batal</button><button type="submit" class="btn btn-success">Simpan stok masuk</button></div></form></div></div></div>

<div class="modal fade" id="modalAdjust" tabindex="-1" role="dialog" aria-labelledby="modalAdjustLabel" aria-hidden="true"><div class="modal-dialog" role="document"><div class="modal-content"><div class="modal-header"><h5 class="modal-title" id="modalAdjustLabel">Penyesuaian stok</h5><button type="button" class="close" data-dismiss="modal" aria-label="Tutup"><span aria-hidden="true">&times;</span></button></div><form method="POST" action="{{ route('stock.adjust') }}"><div class="modal-body">@csrf<input type="hidden" name="_modal" value="adjust"><div class="form-group"><label for="adjust_product_id">Produk</label><select id="adjust_product_id" name="product_id" class="form-control @error('product_id') is-invalid @enderror" required><option value="">Pilih produk</option>@foreach ($products as $product)<option value="{{ $product->id }}" data-stock="{{ $product->stock }}" @selected(old('product_id') === $product->id)>{{ $product->sku }} - {{ $product->name }} (stok {{ $product->stock }})</option>@endforeach</select>@error('product_id')<div class="invalid-feedback">{{ $message }}</div>@enderror</div><div class="alert alert-info" role="status">Stok saat ini: <strong id="adjustCurrentStock">-</strong><br>Selisih: <strong id="adjustDifference">-</strong></div><div class="form-group"><label for="actual_stock">Stok aktual</label><input id="actual_stock" type="number" min="0" name="actual_stock" class="form-control @error('actual_stock') is-invalid @enderror" value="{{ old('actual_stock') }}" required>@error('actual_stock')<div class="invalid-feedback">{{ $message }}</div>@enderror</div><div class="form-group"><label for="adjust_note">Catatan <span class="text-danger">*</span></label><textarea id="adjust_note" name="note" rows="3" class="form-control @error('note') is-invalid @enderror" required>{{ old('note') }}</textarea>@error('note')<div class="invalid-feedback">{{ $message }}</div>@enderror</div></div><div class="modal-footer"><button type="button" class="btn btn-light" data-dismiss="modal">Batal</button><button type="submit" class="btn btn-warning">Simpan penyesuaian</button></div></form></div></div></div>
@endsection

@push('scripts')
<script>
$(function () {
    $('#stock-table').DataTable({ pageLength: 10, order: [[1, 'asc']], responsive: true });
    function updateDifference() { const option = $('#adjust_product_id option:selected'); const current = Number(option.data('stock')); const actual = Number($('#actual_stock').val()); $('#adjustCurrentStock').text(option.val() ? current : '-'); if (!option.val() || $('#actual_stock').val() === '') { $('#adjustDifference').text('-'); return; } const difference = actual - current; $('#adjustDifference').text((difference > 0 ? '+' : '') + difference); }
    $('#adjust_product_id, #actual_stock').on('change input', updateDifference);
    $('#modalAdjust').on('shown.bs.modal', updateDifference);
    @if (old('_modal') === 'receive') $('#modalReceive').modal('show'); @elseif (old('_modal') === 'adjust') $('#modalAdjust').modal('show'); updateDifference(); @endif
});
</script>
@endpush
